package cli

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"github.com/yourorg/minio-manager/internal/config"
	minioc "github.com/yourorg/minio-manager/internal/minio"
)

// importOptions holds the flags of the import command.
type importOptions struct {
	user           string
	password       string
	tls            bool
	output         string
	includeBuiltin bool
}

func newImportCommand() *cobra.Command {
	var opts importOptions

	cmd := &cobra.Command{
		Use:   "import [ENDPOINT]",
		Short: "Export current MinIO state as a YAML config",
		Long: "Connect to a running MinIO cluster and render its buckets, users and\n" +
			"policies as a YAML config (configs/example.yaml schema). The endpoint may\n" +
			"be given as a positional argument or via --minio-endpoint/MINIO_ENDPOINT,\n" +
			"with or without an http(s):// scheme.\n\n" +
			"The output is a starting point: user passwords cannot be read back and must\n" +
			"be filled in (or replaced with vault:// references), and quota/lifecycle/\n" +
			"object-locking are not yet exported. Encrypt the result before committing\n" +
			"it to git.",
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runImport(cmd.Context(), args, opts)
		},
	}

	f := cmd.Flags()
	f.StringVar(&opts.user, "user", "", "MinIO admin access key (falls back to --minio-access-key/MINIO_ACCESS_KEY)")
	f.StringVar(&opts.password, "password", "", "MinIO admin secret key (falls back to --minio-secret-key/MINIO_SECRET_KEY)")
	f.BoolVar(&opts.tls, "tls", false, "Connect over HTTPS")
	f.StringVarP(&opts.output, "output", "o", "", "Write to file (mode 0600) instead of stdout")
	f.BoolVar(&opts.includeBuiltin, "include-builtin-policies", false, "Include MinIO built-in policies in the output")

	return cmd
}

// runImport fetches the current MinIO state and writes it as a YAML config.
func runImport(ctx context.Context, args []string, opts importOptions) error {
	var positional string
	if len(args) == 1 {
		positional = args[0]
	}
	endpoint := firstNonEmpty(positional, viper.GetString("minio-endpoint"))
	if endpoint == "" {
		return fmt.Errorf("endpoint is required: pass it as an argument or via --minio-endpoint")
	}
	host, schemeTLS := normalizeEndpoint(endpoint)

	user := firstNonEmpty(opts.user, viper.GetString("minio-access-key"))
	password := firstNonEmpty(opts.password, viper.GetString("minio-secret-key"))
	if user == "" || password == "" {
		return fmt.Errorf("admin credentials are required: pass --user and --password")
	}

	client, err := minioc.NewClient(minioc.Config{
		Endpoint:  host,
		AccessKey: user,
		SecretKey: password,
		TLS:       opts.tls || schemeTLS,
	})
	if err != nil {
		return err
	}

	cur, err := client.FetchCurrentState(ctx)
	if err != nil {
		return err
	}

	cfg, err := config.FromState(*cur, opts.includeBuiltin)
	if err != nil {
		return err
	}
	cfg.Minio.Endpoint = host
	cfg.Minio.TLS = opts.tls || schemeTLS

	body, err := config.Marshal(cfg)
	if err != nil {
		return err
	}
	document := importHeader(host) + string(body)

	if err := writeOutput(opts.output, document); err != nil {
		return err
	}

	slog.Info("imported MinIO state",
		"endpoint", host,
		"buckets", len(cfg.Buckets),
		"users", len(cfg.Users),
		"policies", len(cfg.Policies),
		"output", outputName(opts.output),
	)
	return nil
}

// importHeader returns the comment block prepended to the generated config.
func importHeader(endpoint string) string {
	return fmt.Sprintf(`# Generated by minio-manager import
# Source:    %s
# Generated: %s
#
# NEXT STEPS before committing:
#   1. Fill in every user 'password' (it cannot be exported from MinIO) or
#      replace it with a vault:// reference, e.g. vault://secret/minio/alice#password
#   2. Set minio.access_key / minio.secret_key (left empty for safety) or
#      provide them via flags/ENV at apply time.
#   3. Review buckets: quota_gb / lifecycle_days / object_locking are not
#      exported yet and default to 0/false.
#   4. Encrypt this file (e.g. sops/age) before pushing to git.

`, endpoint, time.Now().UTC().Format(time.RFC3339))
}

// writeOutput writes the document to a file (mode 0600) or to stdout.
func writeOutput(path, document string) error {
	if path == "" {
		fmt.Print(document)
		return nil
	}
	if err := os.WriteFile(path, []byte(document), 0o600); err != nil {
		return fmt.Errorf("write output %q: %w", path, err)
	}
	return nil
}

func outputName(path string) string {
	if path == "" {
		return "stdout"
	}
	return path
}
